name: Sync Households
on:
  workflow_dispatch:
  schedule:
    # 6 am MST every sunday
    # - cron:  '0 12 * * SUN'
    - cron:  '35 * * * *'
  
jobs:
  sendInvoice:
    env:
      SETTINGS: ${{vars.SETTINGS}}
      GOOGLE_CLIENT_EMAIL: ${{secrets.GOOGLE_CLIENT_EMAIL}}
      GOOGLE_CLIENT_KEY: ${{secrets.GOOGLE_CLIENT_KEY}}
      LDS_USERNAME: ${{secrets.LDS_USERNAME}}
      LDS_PASSWORD: ${{secrets.LDS_PASSWORD}}

    name: Send Latest Invoice
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: yarn --prod

      - name: Send It!
        run: yarn sync